# Generated by Django 3.1.7 on 2021-11-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_auto_20211122_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doacao',
            old_name='username',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='doadores',
            old_name='username',
            new_name='username_id',
        ),
    ]
